### ISSUE TITLE
Double-faced 'names' field order

### ISSUE THREAD

**Issue by tritoch** [lsmoura/mtgjson#135]
Previous double-faced cards always had the front side listed first in the 'names' field - SOI has some variance in this.

**Comment by lsmoura** [comment]
Yeah.. SOI is ordered alphabetically because, sometimes, we cannot know which one is the front and which one is the back.

Here's why:

[410049](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410049) / [410050](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410050)

I'll fix it once SOI hits standard.

**Comment by jenjia** [comment]
I would love this fix on AllSets-x, since my app needs this to work correctly :S
