### ISSUE TITLE
Khans of Tarkir and Fate Reforged are listed as legal in Standard

### ISSUE THREAD

**Issue by dgant** [lsmoura/mtgjson#149]
The new Standard rotation has KTK and FRF rotate out when SOI rotates in: http://whatsinstandard.com/

KTK and FRF have rotated out, but are still listed as legal in MTGJson.

**Comment by tooomm** [comment]
At the moment this is a two step process if I understood it correctly:
1) around pre-release gatherer+mtgjson gets updated with the new set (which is marked not as legal, while the older stays legal --> no updated to legalities at all)
2) around release mtgjson gets updated again (new set is marked legal and old set is not marked legal any longer)


I'm not sure if we need these two steps at all. Why don't you completely update the legalities in the first run @lsmoura when the set is included?
The one week difference is not hurting anybody, it should even be more helpful in most cases. Nobody wants to build decks with cards that are going to rotate out one week later, they are more likely building new decks with new cards that are going to be legal in one week!
The only benefit might be that the database is inaccurate for one week, but well since updating mtgjson not always happens in time anyway and there are many other failures hiding around, this seems to be a very good trade of in terms of usability and maintainability.

**Comment by carlol** [comment]
It seems like it was added the last set without refreshing the legality of previous ones.

**Comment by tooomm** [comment]
@carlol that's always the case... at least that's how I understand the changelog and the updating procedure so far:

>3.3.10
Jan 28, 2016

>**OGW legalities and sets affected by OGW**

<br>
>3.3.9
Jan 22, 2016

>    **OGW legalities**
    Fixed some leftovers of adding {X} mana.

<br>
>3.3.8
Jan 13, 2016

>**OGW Initial version (note that OGW is not yet valid on standard format. Legalities will still be re-updated on the 22nd).**
    New {C} mana symbol.
    Many wordings changed (including Trample).
